name: kafka_zoo
#for linux: on the host, chmod a+rwx -R ./data  XXX as nothing else works
#userns_mode: default
#user: "${DUID}:${DGID}"
services:
  # https://hub.docker.com/r/bitnami/kafka
  # https://github.com/bitnami/containers/blob/main/bitnami/kafka/docker-compose.yml

  zookeeper:
    platform: linux/amd64
    image: bitnami/zookeeper:latest
    deploy: #ignored by compose
      mode: global
    expose:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  #  volumes: 
  #    - $PWD/data/zookeeper:/bitnami/zookeeper

  # https://hub.docker.com/r/bitnami/kafka
  kafka:
    #container_name: kafka
    #user: "${DUID}:${DGID}"
    #user: "nobody"
    #command: id
    platform: linux/amd64
    image: bitnami/kafka:latest
    deploy: #ignored by compose
      mode: global
    #ports:
    #  - 9092:9092
    expose: 
      - 9092
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - BOOTSTRAP_SERVERS=kafka:9092
        #with zookeeper
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      #- BITNAMI_DEBUG=yes
    depends_on:
      - zookeeper
    volumes:
      - $PWD/data/kafka:/bitnami/kafka
      #- vol_kafka:/bitnami/kafka

  xtdb-1: &xtdbcfg
    depends_on:
      - kafka
    platform: linux/amd64
    build:
      context: .    #i.e. using ./Dockerfile
      args:     #these go as ARGS/env into Dockerfile..  
        GROUPID: gx1
    deploy: #ignored by compose
      mode: global
    ports:
      - 3001:3000
    volumes:
      #- vol_x1:/xt/data
      - $PWD/data/xtdb1:/xt/data
      - ${PWD}/data/cp_store:/xt/cp_store
    restart: unless-stopped

  xtdb-2:
    <<: *xtdbcfg
    ports:
      - 3002:3000
    build:
      context: .    #i.e. using ./Dockerfile
      args: 
        GROUPID: gx2
    volumes:
      - $PWD/data/xtdb2:/xt/data
      - ${PWD}/data/cp_store:/xt/cp_store

  xtdb-3:
    <<: *xtdbcfg
    ports:
      - 3003:3000
    build:
      context: .    #i.e. using ./Dockerfile
      args: 
        GROUPID: gx3
    volumes:
      - $PWD/data/xtdb3:/xt/data
      - ${PWD}/data/cp_store:/xt/cp_store

# vim:ts=4:sw=4:expandtab
