a:
	cd .. && python -m xtdb.test_requests
	cd .. && python -m xtdb.testdb
#	PYTHONPATH=.. python testdb.py

#no:
# py-xtdb - https://github.com/joefromct/py-xtdb/tree/main/py_xtdb

# vim:ts=4:sw=4:noexpandtab
